export function renderReport({ url, goal, profile, result }) {
  return [
    `# Agent Dih Report`,
    "",
    `Profile: **${profile.name}**`,
    `URL: ${url}`,
    `Goal: ${goal}`,
    `Mode: ${result.mode}`,
    "",
    "## Scores",
    "",
    `- Fit: ${result.scores.fit}/100`,
    `- Trust: ${result.scores.trust}/100`,
    `- Friction: ${result.scores.friction}/100`,
    `- Conversion: ${result.scores.conversion}/100`,
    "",
    `Verdict: **${result.verdict}**`,
    "",
    "## Journey",
    "",
    ...result.journey.map((item) => `- **${item.step}**: ${item.thought}`),
    "",
    "## Positive Signals",
    "",
    ...(result.signals.length ? result.signals.map((item) => `- ${item}`) : ["- None found in fallback mode."]),
    "",
    "## Concerns",
    "",
    ...(result.concerns.length ? result.concerns.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Next Best Test",
    "",
    "Run with `agent-browser` installed to capture real clicks, screenshots, and page evidence."
  ].join("\n");
}
