export function renderReport({ url, goal, profile, result }) {
  return [
    `# Agent Dih Report`,
    "",
    `Profile: **${profile.name}**`,
    `URL: ${url}`,
    `Goal: ${goal}`,
    `Mode: ${result.mode}`,
    result.pageEvidence?.title ? `Page title: ${result.pageEvidence.title}` : "",
    result.pageEvidence?.description ? `Meta description: ${result.pageEvidence.description}` : "",
    result.pageEvidence?.pricesUsd?.length ? `Detected prices: ${result.pageEvidence.pricesUsd.map((price) => `$${price}`).join(", ")}` : "",
    "",
    "## Scores",
    "",
    `- Fit: ${result.scores.fit}/100`,
    `- Trust: ${result.scores.trust}/100`,
    `- Friction: ${result.scores.friction}/100`,
    `- Conversion: ${result.scores.conversion}/100`,
    "",
    `Verdict: **${result.verdict}**`,
    "",
    "## Journey",
    "",
    ...result.journey.map((item) => `- **${item.step}**: ${item.thought}`),
    "",
    "## Positive Signals",
    "",
    ...(result.signals.length ? result.signals.map((item) => `- ${item}`) : ["- None found in fallback mode."]),
    "",
    "## Concerns",
    "",
    ...(result.concerns.length ? result.concerns.map((item) => `- ${item}`) : ["- None."]),
    "",
    "## Triggered Rules",
    "",
    ...(result.ruleHits?.length
      ? result.ruleHits.map((rule) => `- **${rule.id}** (${rule.severity}): ${rule.reason} Evidence: ${rule.evidence}`)
      : ["- None."]),
    "",
    "## Next Best Test",
    "",
    "Run with `agent-browser` installed to capture real clicks, screenshots, and page evidence."
  ].join("\n");
}
